### ISSUE TITLE
Please correct apples to oranges configuration differences

### ISSUE THREAD

**Issue by gregrluck** [gridgain/yardstick-hazelcast#4]
The https://github.com/gridgain/yardstick-hazelcast/blob/master/config/hazelcast-config.xml is not equivalent to the Ignite one. 

– map.put() instead of map.set() in Hazelcast, while using put() is equivalent to our set() operation because their put() does not have a return value.
– sync backups in Hazelcast for replicas while configuring their own backups as async.

Please change to make them equivalent.

**Comment by ntikhonov** [comment]
Hello,
We've added benchmarks that using set() instead of put(). I want to attract your attention that cache configuration (which defined in hazelcast-config) is changed before running benchmarks, look at https://github.com/gridgain/yardstick-hazelcast/blob/master/src/main/java/org/yardstickframework/hazelcast/HazelcastNode.java. You can compare property files that using for benchmark which published on site.
Hazelcast: https://github.com/gridgain/yardstick-hazelcast/blob/master/config/benchmark.properties
Ignite: https://github.com/apacheignite/yardstick-ignite/blob/master/config/benchmark.properties

**Comment by dsetrakyan** [comment]
We've added benchmarks that use set() instead of put() (had no effect on performance).

There is nothing to fix as far as replicas configuration.

Seems that you do not understand how the Yardstick benchmarking works. The cache configuration (which is defined in hazelcast-config) is changed before running benchmarks by the Yardstick Framework, to ensure that you can run different configuration profiles automatically, one after another. 

Take look at https://github.com/gridgain/yardstick-hazelcast/blob/master/src/main/java/org/yardstickframework/hazelcast/HazelcastNode.java. 

You can compare property files used for benchmarks that are published on Ignite website. They are identical.

Hazelcast: https://github.com/gridgain/yardstick-hazelcast/blob/master/config/benchmark.properties
Ignite: https://github.com/apacheignite/yardstick-ignite/blob/master/config/benchmark.properties
